### ISSUE TITLE
Problema em carregar os bFile

### ISSUE THREAD

**Issue by lucsgtv** [GAD-DIMNT-CPTEC/pyBAM#2]
Nenhuma variavel funciona na função plotField

```
>>> bFile.VarNames
['TOPOGRAPHY', 'LAND SEA ICE MASK', 'LN SURFACE PRESSURE', 'DIVERGENCE', 'VORTICITY', 'SPECIFIC HUMIDITY', 'VIRTUAL TEMPERATURE', 'ROUGHNESS LENGTH', 'SURFACE TEMPERATURE', 'DEEP SOIL TEMPERATURE', 'STORAGE ON CANOPY', 'STORAGE ON GROUND', 'SOIL WETNESS OF SURFACE', 'SOIL WETNESS OF ROOT ZONE', 'SOIL WETNESS OF DRAINAGE ZONE', 'TEMPERATURE AT 2-M FROM SURFACE', 'SPECIFIC HUMIDITY AT 2-M FROM SURFACE', 'ZONAL WIND AT 10-M FROM SURFACE', 'MERID WIND AT 10-M FROM SURFACE', 'MASK VEGETATION', 'MASK SOIL TEXTURE CLASSES', 'PARTIAL OXYGEN DENSITY', 'SURFACE SOIL TEMPERATURE', 'VEGETATION COVER', 'SNOW DEPTH', 'LIQ MIXING RATIO PROGNOSTIC', 'ICE MIXING RATIO PROGNOSTIC', 'CLOUD TOTAL PROGNOSTIC']
>>> bFile.plotField('VIRTUAL TEMPERATURE', zlevel=1)
 :: SRead1D_( ... ): error to read field,           -1
 :: SRead1D_( ... ):End of file
 :: DGetFLD_1D( ... ): error to read file ::[2024091006/GFCTCPT20240910062024091006F.icn.TQ0299L064 ],           -1
 CFB_DEBUG#1, MnWv=       90300
 CFB_DEBUG#1, MnWv=       90300
Error to get field VIRTUAL TEMPERATURE -1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pybam-files/lib/python3.7/site-packages/pyBAM-1.0-py3.7-linux-x86_64.egg/pyBAM/__main__.py", line 400, in plotField
    img = field.plot(transform=ccrs.PlateCarree(), **kwargs)
AttributeError: 'NoneType' object has no attribute 'plot'
>>> bFile.
bFile.FNumber      bFile.close(       bFile.getField(    bFile.initSpec     bFile.lons         bFile.nlat         bFile.plotField(
bFile.VarNames     bFile.ftype        bFile.getField3D(  bFile.lats         bFile.mode         bFile.nlevels      bFile.spec2grid(
bFile.binary       bFile.gOField(     bFile.header       bFile.levels       bFile.nVars        bFile.nlon


>>> bFile.plotField('VORTICITY', zlevel=1)
 :: SRead1D_( ... ): error to read field,           -1
 :: SRead1D_( ... ):End of file
 :: DGetFLD_1D( ... ): error to read file ::[2024091006/GFCTCPT20240910062024091006F.icn.TQ0299L064 ],           -1
 CFB_DEBUG#1, MnWv=       90300
 CFB_DEBUG#1, MnWv=       90300
Error to get field VORTICITY -1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pybam-files/lib/python3.7/site-packages/pyBAM-1.0-py3.7-linux-x86_64.egg/pyBAM/__main__.py", line 400, in plotField
    img = field.plot(transform=ccrs.PlateCarree(), **kwargs)
AttributeError: 'NoneType' object has no attribute 'plot'
```

**Comment by cfbastarz** [comment]
Olá @lucsgtv, eu verifiquei os requisitos para a utilização da libsigioBAM e do pyBAM e encontrei que há uma limitação no suporte das versões do GCC. Na minha máquina, Kubuntu Linux 24.10 (`Kernel Linux 6.11.0-9-generic #9-Ubuntu SMP PREEMPT_DYNAMIC`). As versões do GCC que podem ser instaladas nessa versão do Ubuntu, são:

* 11.5.0
* 12.4.0
* 13.3.0
* 14.2.0

Dentre estas versões, apenas a versão 14.2.0 é a que não está funcionando com o libsigioBAM, que é a biblioteca responsável por efetivamente ler os arquivos binários de previsões do modelo BAM. Com as demais versões, não há problemas. Verifique qual versão do GCC você tem instalado na sua máquina (no seu caso com o WSL), o que pode ser feito com os seguintes comandos:

```
gcc --version
g++ --version
gfortran --version
```

Eu recomendo sempre ter as versões dos compiladores gcc, g++, gfortran com as mesmas versões. Você pode ter múltiplas versões do GCC instaladas no seu computador e pode alternar entre as versões a serem utilizadas da seguinte forma, no Ubuntu e derivados:

#### Instalando diferentes versões do GCC

```
sudo apt install gcc-11 gcc-12 gcc-13 gcc-14
sudo apt install g++-11 g++-12 g++-13 g++-14
sudo apt install gfortran-11 gfortran-12 gfortran-13 gfortran-14
```

#### Configurando as diferentes versões do GCC

```
sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++
sudo update-alternatives --remove-all gfortran

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 20
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 30
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 40

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 30
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 40

sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-11 10
sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-12 20
sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-13 30
sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-14 40
```

Por fim, execute os comandos a seguir para escolher qual versão dos compiladores GCC a serem utilizados por padrão:

```
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
sudo update-alternatives --config gfortran
```

Depois de escolher a versão desejadas (para a compilação da biblioteca `libsigioBAM` e do `pyBAM`, escolha as versões 11, 12 ou 13 dos compiladores do GCC), proceda com a compilação do `libsigioBAM`:

```
cd ~/libsigiobam-1.1
./configure --prefix=/opt/libsigiobam-1.1
make
sudo make install
```

**Nota:** Observe que a biblioteca `libsigioBAM` foi instalada em `/opt`, o que requer que o comando `make install` seja executado com o comando `sudo` na frente. Se você escolher um outro local dentro do seu `$HOME`, não será necessário utilizar o comando `sudo`.

Após, inclua no seu `~/.bashrc` ou `~/.profile` as seguintes linhas:

```
export SIGIOBAM=/opt/libsigiobam-1.1
export LD_LIBRARY_PATH=/${SIGIOBAM}/lib:${LD_LIBRARY_PATH}
```

Depois, abra uma nova seção do terminal e verifique se a variável `$SIGIOBAM` possui o valor correto:

```
echo $SIGIOBAM
```

O próximo passo será a criação de um ambiente do conda para a instalação do `pyBAM`.

**Nota:** Observe que é necessário que a instalação do `pyBAM` seja feita com a mesma versão do compilador GCC utilizado para a compilação da biblioteca `libsigioBAM`:

```
conda create -n pyBAM python=3.7.6

conda activate pyBAM
conda install numpy
conda install -c conda-forge xarray dask netCDF4 bottleneck
conda install matplotlib
conda install -c conda-forge cartopy
```

Dentro do ambiente `pyBAM` criado, execute os comandos:

```
cd pyBAM
python setup.py build
python setup.py install
```

Depois disso tudo, teste novamente a abertura do arquivo e as funções de plotagem do `pyBAM`.
